### PR TITLE
2D and 3D vehicle definitions

### PR DESCRIPTION
**Pull request by Pedro-Roque**
Adding 2D and 3D platform definitions for 3DoF and 6DoF setups in simulation.

### CODE REVIEW

**Review by Jaeyoung-Lim — COMMENTED** [review]
where are the prefix that you are mentioning?

**Comment by Pedro-Roque** [comment]
sc_ is now the prefix, instead of sr_ or ss_

**Comment by Jaeyoung-Lim** [comment]
@Pedro-Roque But what was affected? I don't see any of `sr_` or `ss_` being changed in the PR

**Comment by Pedro-Roque** [comment]
Sorry @Jaeyoung-Lim my bad, that change has been done before, this PR is mostly for adding the 2D and 3D vehicles and some small changes to the CMakeLists (I noticed that old installation files were being kept and not overwritten, so I had a quick fix for that).

Best,
Pedro

**Pull request merged**
